### ISSUE TITLE
Documentation.

### ISSUE THREAD

**Issue by weinbe58** [mgbukov/dynamicQL#1]
Maybe it would be nice to add a short text file showing what each file does and showing how to run/modify the RL and SD code for other problems.

**Comment by alexandreday** [comment]
Agreed, I will try to rearrange things and clean up the code, then will produce a small documentation with short examples for the SD. Marin perhaps can do the same for the RL.

**Comment by mgbukov** [comment]
OK, I put in some comments. People should be able how to run it with some rather not so big effort provided they know what Reinforcement Learning is, cuz all lines in the code are commented.

I don't think this is ready at the level of a black box, but it's not meant to be one.
